server.servlet.context-path=/api

spring.application.name=azure-aks-deploy-with-gh-and-bicep-java-api

# Specify the DNS URI of your Azure Cosmos DB.
spring.cloud.azure.cosmos.endpoint=${COSMOS_ENDPOINT:https://localhost:8081}
spring.cloud.azure.cosmos.key=${COSMOS_KEY:C2y6yDjf5/R+ob0N8A7Cgv30VRDJIWEHLM+4QDU5DE2nQ9nDuVTqobD4b8mGGyPMbIZnqyMsEcaGQy67XIw/Jw==}

# Specify the name of your database.
spring.cloud.azure.cosmos.database=contosoaccounttest
spring.cloud.azure.cosmos.populate-query-metrics=true

#necessary to connect to the local cosmos db
spring.cloud.azure.cosmos.connection-mode=${COSMOS_CONN_MODE:gateway}